apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: CHATBOT
  annotations:
    github.com/project-slug: Backstage-EMC/CHATBOT
spec:
  type: other
  lifecycle: unknown
  owner: Backstage-EMC
